version: '2'
services:
  mysql:
    # network_mode: myNetwork
    container_name: coconut
    restart: always
    image: mysql:latest # ? คล้ายๆกับ lib แต่มันคือ image ที่ต้องการทำงานกับระบบที่กำลังทำงานอยู่
    environment:
      MYSQL_ROOT_PASSWORD: '' # ? ให้ root ไม่มี password
      # MYSQL_USER: 'root'
      # MYSQL_PASS: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql